### PR TITLE
Support Telegram.Bot v17.0.0

### PR DESCRIPTION
**Pull request by JasonKhew96**
- ~~Fix int64 Unsupported User bug~~
- Didn't test all of them, bug expected

# KNOWN ISSUE(S)
- ~~Restart loop~~ (Fixed)

### CODE REVIEW

**Comment by Elepover** [comment]
Thanks for your PR.

All my open-source projects have been currently laid aside due to personal reasons.

You can maintain your own fork of pmcenter if you like.

There're many parts of pmcenter that had failed to follow standards or conventions, or used dirty implementations, and it needs a major revamp to get back onto the right track. I'm not merging this PR as the development of pmcenter has been basically halted.

**Comment by gadspeed233** [comment]
正在上传 t2{b7f6e79} (a594252e-8c8a-4027-a27d-ef9c915aa96d id=0x7f0a039e tag=BaseCommentFragment)…

**Comment by luojiangpeng** [comment]
cc66e3b084ed52f768cf12c03cf891f

**Comment by luojiangpeng** [comment]
cc66e3b084ed52f768cf12c03cf891f

**Pull request closed without merging**
